### ISSUE TITLE
Mississippi Scraper doesn't properly separate double headliner shows

### ISSUE THREAD

**Issue by rattboi** [demophoon/trello-concert-tracker#1]
Ex: Headliner: "EMA / The Blow"

Last.fm playcount for said artist is 0, because that's not a real artist. Should be separated into EMA + The Blow. This is a missed show for me.

**Comment by rattboi** [comment]
Fixed by https://github.com/demophoon/trello-concert-tracker/pull/4

**Comment by demophoon** [comment]
Merged into master @ 41b7b789dccd433828f7062e004d14a631385c81
